theme: jekyll-theme-primer
title: Willy Yu - Full Stack Engineer CV
description: Personal CV Website
exclude:
  - src/
  - node_modules/
  - dist/
  - docs/
  - cv/
  - public/
  - package.json
  - package-lock.json
  - vite.config.js
  - vite.config.ts
  - .github/
  - Gemfile.lock
